### ISSUE TITLE
Custom Action in NAT

### ISSUE THREAD

**Issue by chises** [fwbuilder/fwbuilder#64]
hello all and thank you for keeping this tool alive :)

i have a (simple) question:
is it possible to create a custom action in NAT policy? i want to generate something like: 
`iptables -t nat -I PREROUTING --dst IP -p tcp --dport 123 -j REDIRECT --to-ports 321`

**Comment by rephlex** [comment]
yes, you can use the firewall epilogue.
it's a text box that allows you to enter any script code that will be executed when you install the firewall.

Note: be on the safe side and give it the full path (e.g. "/sbin/iptables") instead of just "iptables".

![bildschirmfoto von 2018-09-24 15-14-04](https://user-images.githubusercontent.com/1290798/45954161-8fd45d00-c00c-11e8-9ff7-958d8a945bdd.png)

![bildschirmfoto von 2018-09-24 15-14-30](https://user-images.githubusercontent.com/1290798/45954170-9531a780-c00c-11e8-8b93-e80b1e6829a1.png)
